### ISSUE TITLE
The baidu Dist can't use

### ISSUE THREAD

**Issue by Wangrui-berry** [aa1234241/lld_submit#3]
The file has been past due. Could you please update it?

**Comment by aa1234241** [comment]
I've checked the link is still valid, may you try again?

**Comment by Wangrui-berry** [comment]
Sorry to disturb you.  I have found it.
And what I want to ask is do you change anything in the model (res18)? 
In the competition, you have mainly modified the dataset, are there important details?

**Comment by aa1234241** [comment]
I do not change the model structure.  Model ensemble is important.

**Comment by Wangrui-berry** [comment]
OK. Thanks you very much.
